version: '3'

services:
  postgresdb:
    image: 'bitnami/postgresql:16.0.0'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignite-elixir-rockelivery
    ports:
      - 5432:5432
    volumes:
      - 'postgres_data:/bitnami/postgresql'

volumes:
  postgres_data:
