name: Deploy

on:
  workflow_run: 
    workflows: ["Test"]
    types: 
      - completed
    branches: ["main"]

permissions: 
    contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: gigalixir deploy
        uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_CLEAN: true
          GIGALIXIR_APP: every-dimgray-parrot
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}